<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Totem</RootNamespace>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EventStore.Client.Grpc" Version="22.0.0" />
        <PackageReference Include="EventStore.Client.Grpc.PersistentSubscriptions" Version="22.0.0" />
        <PackageReference Include="EventStore.Client.Grpc.Streams" Version="22.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
        <PackageReference Include="Microsoft.Toolkit.HighPerformance" Version="7.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Totem.Messages\Totem.Messages.csproj" />
    </ItemGroup>

</Project>