<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Totem</RootNamespace>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Totem.Core.Messages\Totem.Core.Messages.csproj" />
      <ProjectReference Include="..\Totem.Core.Runtime\Totem.Core.Runtime.csproj" />
      <ProjectReference Include="..\Totem.Tsp.Messages\Totem.Tsp.Messages.csproj" />
    </ItemGroup>

</Project>
