using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Quantum.Wasp.Models.Common;

namespace Quantum.Wasp.Models.Customers;

public class CustomerInfo
{
    public int RowNumber { get; set; }
    public int ImportRowNumber { get; set; }
    public int? CustomerId { get; set; }
    public string CustomerNumber { get; set; }
    public string CustomerName { get; set; }
    public string CustomerDepartment { get; set; }
    public string CustomerCompanyName { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Department { get; set; }
    public string SiteName { get; set; }
    public int? CustomerRecordStatus { get; set; }
    public List<AddressInfo> Addresses { get; set; }
    public List<DcfValueInfo> CustomFields { get; set; }
    public bool HasAttachment { get; set; }
    public bool IsAutogeneratedCustomerNumber { get; set; }
    public List<string> AttachmentsToAdd { get; set; }
    public List<string> AttachmentsToDelete { get; set; }
    public List<KeyValuePair<string, string>> AttachmentNames { get; set; }
    public List<string> ApplicableFields { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement> AdditionalData { get; set; }
}
