<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Totem</RootNamespace>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Hosting\**" />
      <EmbeddedResource Remove="Hosting\**" />
      <None Remove="Hosting\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Hosting\SameOriginCredentialsHandler.cs" />
      <Compile Include="Hosting\TotemTspClientBuilderExtensions.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Connections.Client" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Totem.Web.Client\Totem.Web.Client.csproj" />
    </ItemGroup>

</Project>
