<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CA1811;IDE0051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Totem.Timeline\Totem.Timeline.csproj" />
  </ItemGroup>

</Project>
